server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # React Router: /about jaise routes pe refresh karne par bhi index.html mile
    location / {
        try_files $uri $uri/ /index.html;
    }
}
